Repository Freshly/spicerack, pull requests merged in 2019-06, with the labels that each got.

#183 Configurable
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/lib/around_the_world/version.rb
  lib/spicerack.rb
  lib/spicerack/configurable.rb
  lib/spicerack/configurable/config_builder.rb
  lib/spicerack/configurable/reader.rb
  lib/spicerack/rspec/custom_matchers.rb
  lib/spicerack/rspec/custom_matchers/define_config_option.rb
  lib/spicerack/version.rb
  redis_hash/lib/redis_hash/version.rb
  rspice/lib/rspice/version.rb
  rspice/rspice.gemspec
  short_circu_it/lib/short_circu_it/version.rb
  spec/spicerack/configurable/config_builder_spec.rb
  spec/spicerack/configurable/reader_spec.rb
  spec/spicerack/configurable_spec.rb
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  spicerack.gemspec
  tablesalt/lib/tablesalt/version.rb
  technologic/lib/technologic/version.rb
Labels: Feature

#193 Typo Fix
  CHANGELOG.md
Labels: Correction

#195 Log Spec Helper Fix
  rspice/CHANGELOG.md
  rspice/lib/rspice/shared_examples/an_instrumented_event.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/rspec/shared_examples/a_logged_event_with_severity.rb
Labels: Feature

#196 Release 0.14.2
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/lib/technologic/version.rb
Labels: Release

#197 Release 0.14.2
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/shared_examples/an_instrumented_event.rb
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/rspec/shared_examples/a_logged_event_with_severity.rb
  technologic/lib/technologic/version.rb
Labels: Release
