Repository Freshly/spicerack, pull requests merged in 2019-05, with the labels that each got.

#59 Update Rubocop to latest version
  Gemfile.lock
  spicerack-styleguide/rubocop.yml
  spicerack-styleguide/spicerack-styleguide.gemspec
  spicerack.gemspec
Labels: Maintenance

#61 Callforth: Configuration
  callforth/lib/callforth.rb
  callforth/lib/callforth/config_options.rb
  callforth/lib/callforth/railtie.rb
  callforth/lib/callforth/setup.rb
  callforth/lib/generators/callforth/initializer/USAGE
  callforth/lib/generators/callforth/initializer/initializer_generator.rb
  callforth/lib/generators/callforth/initializer/templates/initializer.rb.erb
  callforth/spec/callforth/config_options_spec.rb
  callforth/spec/callforth/setup_spec.rb
  technologic/lib/generators/technologic/initializer/USAGE
Labels: Precursor

#62 Callforth: Encoder Core
  Gemfile.lock
  callforth/README.md
  callforth/callforth.gemspec
  callforth/lib/callforth.rb
  callforth/lib/callforth/encoder.rb
  callforth/spec/callforth/encoder_spec.rb
  callforth/spec/callforth_spec.rb
  callforth/spec/spec_helper.rb
  callforth/spec/support/shared_contexts/with_target_class_having_method.rb
  callforth/spec/support/shared_examples/an_encoder.rb
  rspice/lib/rspice.rb
  rspice/lib/rspice/shared_examples/a_class_pass_method.rb
  shared/spec_helper.rb
  technologic/README.md
  technologic/technologic.gemspec
Labels: Precursor

#66 Remove Callforth
  CHANGELOG.md
  Gemfile.lock
  README.md
  Rakefile
  callforth/.rspec
  callforth/CHANGELOG.md
  callforth/LICENSE.txt
  callforth/README.md
  callforth/Rakefile
  callforth/bin/console
  callforth/bin/setup
  callforth/callforth.gemspec
  callforth/lib/callforth.rb
  callforth/lib/callforth/config_options.rb
  callforth/lib/callforth/encoder.rb
  callforth/lib/callforth/railtie.rb
  callforth/lib/callforth/setup.rb
  callforth/lib/callforth/version.rb
  callforth/lib/generators/callforth/initializer/USAGE
  callforth/lib/generators/callforth/initializer/initializer_generator.rb
  callforth/lib/generators/callforth/initializer/templates/initializer.rb.erb
  callforth/spec/callforth/config_options_spec.rb
  callforth/spec/callforth/encoder_spec.rb
  callforth/spec/callforth/setup_spec.rb
  callforth/spec/callforth_spec.rb
  callforth/spec/spec_helper.rb
  callforth/spec/support/shared_contexts/with_target_class_having_method.rb
  callforth/spec/support/shared_examples/an_encoder.rb
  lib/spicerack.rb
  spicerack.gemspec
Labels: Correction

#67 Fix Codeclimate
  .codeclimate.yml
Labels: Correction

#70 Release 0.8.0
  CHANGELOG.md
  around_the_world/CHANGELOG.md
  rspice/CHANGELOG.md
  short_circu_it/CHANGELOG.md
  spicerack-styleguide/CHANGELOG.md
  table_salt/CHANGELOG.md
  technologic/CHANGELOG.md
Labels: Maintenance

#71 Instructor
  CHANGELOG.md
  README.md
  Rakefile
  instruct/CHANGELOG.md
  instructor/.rspec
  instructor/CHANGELOG.md
  instructor/LICENSE.txt
  instructor/README.md
  instructor/Rakefile
  instructor/bin/console
  instructor/bin/setup
  instructor/instructor.gemspec
  instructor/lib/instructor.rb
  instructor/lib/instructor/version.rb
  instructor/spec/instructor_spec.rb
  instructor/spec/spec_helper.rb
  lib/spicerack.rb
Labels: Refactoring

#72 Changelog Cleanup
  CHANGELOG.md
Labels: Maintenance

#73 Tabelsalt
  CHANGELOG.md
  Gemfile.lock
  README.md
  Rakefile
  lib/spicerack.rb
  spicerack.gemspec
  table_salt/lib/table_salt.rb
  tablesalt/.rspec
  tablesalt/CHANGELOG.md
  tablesalt/LICENSE.txt
  tablesalt/README.md
  tablesalt/Rakefile
  tablesalt/bin/console
  tablesalt/bin/setup
  tablesalt/lib/tablesalt.rb
  tablesalt/lib/tablesalt/version.rb
  tablesalt/spec/spec_helper.rb
  tablesalt/spec/tablesalt_spec.rb
  tablesalt/tablesalt.gemspec
Labels: Refactoring

#74 Release 0.8.1
  CHANGELOG.md
  Gemfile.lock
  README.md
  SPICERACK_VERSION
  around_the_world/lib/around_the_world/version.rb
  instructor/lib/instructor/version.rb
  lib/spicerack/version.rb
  rspice/lib/rspice/version.rb
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/lib/tablesalt/version.rb
  technologic/lib/technologic/version.rb
Labels: Release

#75 Release 0.8.1
  CHANGELOG.md
  Gemfile.lock
  README.md
  Rakefile
  SPICERACK_VERSION
  around_the_world/lib/around_the_world/version.rb
  instructor/lib/instructor/version.rb
  lib/spicerack.rb
  lib/spicerack/version.rb
  rspice/lib/rspice/version.rb
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  spicerack.gemspec
  table_salt/lib/table_salt.rb
  tablesalt/.rspec
  tablesalt/CHANGELOG.md
  tablesalt/LICENSE.txt
  tablesalt/README.md
  tablesalt/Rakefile
  tablesalt/bin/console
  tablesalt/bin/setup
  tablesalt/lib/tablesalt.rb
  tablesalt/lib/tablesalt/version.rb
  tablesalt/spec/spec_helper.rb
  tablesalt/spec/tablesalt_spec.rb
  tablesalt/tablesalt.gemspec
  technologic/lib/technologic/version.rb
Labels: Release

#76 Instructor/dependencies
  Gemfile.lock
  instructor/instructor.gemspec
  instructor/lib/instructor.rb
  instructor/lib/instructor/base.rb
  instructor/spec/instructor/base_spec.rb
Labels: Precursor

#77 Instructor: Implementation
  instructor/lib/instructor/base.rb
  instructor/lib/instructor/concerns/arguments.rb
  instructor/lib/instructor/concerns/attributes.rb
  instructor/lib/instructor/concerns/callbacks.rb
  instructor/lib/instructor/concerns/core.rb
  instructor/lib/instructor/concerns/defaults.rb
  instructor/lib/instructor/concerns/options.rb
  instructor/lib/instructor/concerns/string.rb
  instructor/spec/instructor/arguments_spec.rb
  instructor/spec/instructor/attributes_spec.rb
  instructor/spec/instructor/base_spec.rb
  instructor/spec/instructor/callbacks_spec.rb
  instructor/spec/instructor/core_spec.rb
  instructor/spec/instructor/defaults_spec.rb
  instructor/spec/instructor/options_spec.rb
  instructor/spec/instructor/string_spec.rb
  instructor/spec/spec_helper.rb
  instructor/spec/support/shared_context/with_an_example_instructor.rb
  instructor/spec/support/shared_examples/a_class_which_defines_into_a_class_collection.rb
  instructor/spec/support/shared_examples/a_class_with_attributes_having_default_values.rb
  technologic/spec/technologic/logger_spec.rb
Labels: Feature

#78 Instructor: spec_helper
  Gemfile.lock
  instructor/lib/instructor/custom_matchers.rb
  instructor/lib/instructor/custom_matchers/define_argument.rb
  instructor/lib/instructor/custom_matchers/define_attribute.rb
  instructor/lib/instructor/custom_matchers/define_option.rb
  instructor/lib/instructor/shoulda_matcher_helper.rb
  instructor/lib/instructor/spec_helper.rb
  instructor/spec/spec_helper.rb
  spicerack.gemspec
Labels: Feature

#79 Instructor: Integration Test
  instructor/spec/integration/bottles_on_the_wall_spec.rb
  instructor/spec/spec_helper.rb
  instructor/spec/support/test_classes/bottles_on_the_wall.rb
  shared/spec_helper.rb
Labels: Feature

#80 Release 0.8.2
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/lib/around_the_world/version.rb
  instructor/CHANGELOG.md
  instructor/lib/instructor/version.rb
  lib/spicerack/version.rb
  rspice/lib/rspice/version.rb
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/lib/tablesalt/version.rb
  technologic/lib/technologic/version.rb
Labels: Release

#81 Release 0.8.2
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/lib/around_the_world/version.rb
  instructor/CHANGELOG.md
  instructor/instructor.gemspec
  instructor/lib/instructor.rb
  instructor/lib/instructor/base.rb
  instructor/lib/instructor/concerns/arguments.rb
  instructor/lib/instructor/concerns/attributes.rb
  instructor/lib/instructor/concerns/callbacks.rb
  instructor/lib/instructor/concerns/core.rb
  instructor/lib/instructor/concerns/defaults.rb
  instructor/lib/instructor/concerns/options.rb
  instructor/lib/instructor/concerns/string.rb
  instructor/lib/instructor/custom_matchers.rb
  instructor/lib/instructor/custom_matchers/define_argument.rb
  instructor/lib/instructor/custom_matchers/define_attribute.rb
  instructor/lib/instructor/custom_matchers/define_option.rb
  instructor/lib/instructor/shoulda_matcher_helper.rb
  instructor/lib/instructor/spec_helper.rb
  instructor/lib/instructor/version.rb
  instructor/spec/instructor/arguments_spec.rb
  instructor/spec/instructor/attributes_spec.rb
  instructor/spec/instructor/base_spec.rb
  instructor/spec/instructor/callbacks_spec.rb
  instructor/spec/instructor/core_spec.rb
  instructor/spec/instructor/defaults_spec.rb
  instructor/spec/instructor/options_spec.rb
  instructor/spec/instructor/string_spec.rb
  instructor/spec/integration/bottles_on_the_wall_spec.rb
  instructor/spec/spec_helper.rb
  instructor/spec/support/shared_context/with_an_example_instructor.rb
  instructor/spec/support/shared_examples/a_class_which_defines_into_a_class_collection.rb
  instructor/spec/support/shared_examples/a_class_with_attributes_having_default_values.rb
  instructor/spec/support/test_classes/bottles_on_the_wall.rb
  lib/spicerack/version.rb
  rspice/lib/rspice/version.rb
  shared/spec_helper.rb
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  spicerack.gemspec
  tablesalt/lib/tablesalt/version.rb
  technologic/lib/technologic/version.rb
  technologic/spec/technologic/logger_spec.rb
Labels: Release

#82 Release 0.8.2
  around_the_world/CHANGELOG.md
  rspice/CHANGELOG.md
  short_circu_it/CHANGELOG.md
  spicerack-styleguide/CHANGELOG.md
  tablesalt/CHANGELOG.md
  technologic/CHANGELOG.md
Labels: Correction

#83 Instructor: Copy Missing Test
  instructor/spec/instructor/defaults/value_spec.rb
Labels: Feature

#84 Instructor: Shared Examples
  instructor/lib/instructor/shared_examples.rb
  instructor/lib/instructor/shared_examples/an_instructor_with_a_class_collection_attribute.rb
  instructor/lib/instructor/spec_helper.rb
  instructor/spec/instructor/options_spec.rb
Labels: Feature

#85 Release 0.8.3
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  instructor/CHANGELOG.md
  instructor/lib/instructor/version.rb
  lib/spicerack/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#86 Release 0.8.3
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  instructor/CHANGELOG.md
  instructor/lib/instructor/shared_examples.rb
  instructor/lib/instructor/shared_examples/an_instructor_with_a_class_collection_attribute.rb
  instructor/lib/instructor/spec_helper.rb
  instructor/lib/instructor/version.rb
  instructor/spec/instructor/defaults/value_spec.rb
  instructor/spec/instructor/options_spec.rb
  lib/spicerack/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#87 Tablesalt: RedisHash
  tablesalt/lib/tablesalt.rb
  tablesalt/lib/tablesalt/redis_hash_base.rb
  tablesalt/spec/tablesalt/redis_hash_base_spec.rb
Labels: Precursor

#89 Tablesalt: RedisHash: Essentials
  Gemfile.lock
  rspice/lib/rspice.rb
  tablesalt/lib/tablesalt.rb
  tablesalt/lib/tablesalt/redis_hash/callbacks.rb
  tablesalt/lib/tablesalt/redis_hash/core.rb
  tablesalt/lib/tablesalt/redis_hash_base.rb
  tablesalt/spec/tablesalt/redis_hash/callbacks_spec.rb
  tablesalt/spec/tablesalt/redis_hash/core_spec.rb
  tablesalt/spec/tablesalt/redis_hash_base_spec.rb
  tablesalt/tablesalt.gemspec
Labels: Precursor

#90 Tablesalt: RedisHash: CachedHash
  shared/spec_helper.rb
  tablesalt/lib/tablesalt/redis_hash/cached_hash.rb
  tablesalt/lib/tablesalt/redis_hash/callbacks.rb
  tablesalt/lib/tablesalt/redis_hash/core.rb
  tablesalt/lib/tablesalt/redis_hash_base.rb
  tablesalt/spec/spec_helper.rb
  tablesalt/spec/support/shared_context/with_an_example_redis_hash.rb
  tablesalt/spec/support/shared_context/with_data_in_redis.rb
  tablesalt/spec/tablesalt/redis_hash/cached_hash_spec.rb
  tablesalt/spec/tablesalt/redis_hash/callbacks_spec.rb
  tablesalt/spec/tablesalt/redis_hash/core_spec.rb
  tablesalt/spec/tablesalt/redis_hash_base_spec.rb
Labels: Precursor

#91 Tablesalt: RedisHash: Rename Cache
  tablesalt/lib/tablesalt/redis_hash/accessors.rb
  tablesalt/lib/tablesalt/redis_hash/cached_hash.rb
  tablesalt/lib/tablesalt/redis_hash/core.rb
  tablesalt/lib/tablesalt/redis_hash_base.rb
  tablesalt/spec/tablesalt/redis_hash/accessors_spec.rb
  tablesalt/spec/tablesalt/redis_hash/cached_hash_spec.rb
  tablesalt/spec/tablesalt/redis_hash/core_spec.rb
  tablesalt/spec/tablesalt/redis_hash_base_spec.rb
Labels: Correction, Refactoring

#92 Tablesalt: RedisHash: Core Delegation
  tablesalt/lib/tablesalt/redis_hash/core.rb
  tablesalt/spec/tablesalt/redis_hash/core_spec.rb
Labels: Precursor

#93 Tablesalt: RedisHash: Identity
  tablesalt/lib/tablesalt/redis_hash/accessors.rb
  tablesalt/lib/tablesalt/redis_hash/core.rb
  tablesalt/lib/tablesalt/redis_hash/identity.rb
  tablesalt/lib/tablesalt/redis_hash_base.rb
  tablesalt/spec/support/shared_context/with_an_example_redis_hash.rb
  tablesalt/spec/support/shared_context/with_data_in_redis.rb
  tablesalt/spec/tablesalt/redis_hash/core_spec.rb
  tablesalt/spec/tablesalt/redis_hash/identity_spec.rb
  tablesalt/spec/tablesalt/redis_hash_base_spec.rb
Labels: Feature

#94 Tablesalt: RedisHash: Comparisons
  tablesalt/lib/tablesalt/redis_hash/accessors.rb
  tablesalt/lib/tablesalt/redis_hash/comparisons.rb
  tablesalt/lib/tablesalt/redis_hash/identity.rb
  tablesalt/lib/tablesalt/redis_hash_base.rb
  tablesalt/spec/support/shared_context/with_an_example_redis_hash.rb
  tablesalt/spec/support/shared_context/with_data_in_redis.rb
  tablesalt/spec/tablesalt/redis_hash/accessors_spec.rb
  tablesalt/spec/tablesalt/redis_hash/comparisons_spec.rb
  tablesalt/spec/tablesalt/redis_hash/identity_spec.rb
  tablesalt/spec/tablesalt/redis_hash_base_spec.rb
Labels: Feature, Refactoring

#95 Tablesalt: RedisHash: Delegators
  tablesalt/lib/tablesalt/redis_hash/comparisons.rb
  tablesalt/lib/tablesalt/redis_hash/identity.rb
  tablesalt/spec/tablesalt/redis_hash/comparisons_spec.rb
  tablesalt/spec/tablesalt/redis_hash/identity_spec.rb
Labels: Feature

#96 Tablesalt: RedisHash: Accessors
  tablesalt/lib/tablesalt/redis_hash/accessors.rb
  tablesalt/spec/tablesalt/redis_hash/accessors_spec.rb
Labels: Feature

#97 Tablesalt: RedisHash: Predicates
  tablesalt/lib/tablesalt/redis_hash/predicates.rb
  tablesalt/lib/tablesalt/redis_hash_base.rb
  tablesalt/spec/tablesalt/redis_hash/accessors_spec.rb
  tablesalt/spec/tablesalt/redis_hash/predicates_spec.rb
  tablesalt/spec/tablesalt/redis_hash_base_spec.rb
Labels: Feature

#98 Tablesalt: RedisHash: Deletions
  tablesalt/lib/tablesalt/redis_hash/deletions.rb
  tablesalt/lib/tablesalt/redis_hash_base.rb
  tablesalt/spec/tablesalt/redis_hash/deletions_spec.rb
  tablesalt/spec/tablesalt/redis_hash_base_spec.rb
Labels: Feature

#99 Tablesalt: RedisHash: Insertions
  tablesalt/lib/tablesalt/redis_hash/deletions.rb
  tablesalt/lib/tablesalt/redis_hash/insertions.rb
  tablesalt/lib/tablesalt/redis_hash_base.rb
  tablesalt/spec/tablesalt/redis_hash/deletions_spec.rb
  tablesalt/spec/tablesalt/redis_hash/insertions_spec.rb
  tablesalt/spec/tablesalt/redis_hash_base_spec.rb
Labels: Feature

#100 Tablesalt: RedisHash: Enumerators
  tablesalt/lib/tablesalt/redis_hash/enumerators.rb
  tablesalt/lib/tablesalt/redis_hash_base.rb
  tablesalt/spec/tablesalt/redis_hash/enumerators_spec.rb
  tablesalt/spec/tablesalt/redis_hash_base_spec.rb
Labels: Feature

#101 Tablesalt: RedisHash: Mutations
  tablesalt/lib/tablesalt/redis_hash/mutations.rb
  tablesalt/lib/tablesalt/redis_hash_base.rb
  tablesalt/spec/tablesalt/redis_hash/mutations_spec.rb
  tablesalt/spec/tablesalt/redis_hash_base_spec.rb
Labels: Feature

#103 Tablesalt: RedisHash: Default
  tablesalt/lib/tablesalt/redis_hash/default.rb
  tablesalt/lib/tablesalt/redis_hash_base.rb
  tablesalt/spec/tablesalt/redis_hash/default_spec.rb
  tablesalt/spec/tablesalt/redis_hash_base_spec.rb
Labels: Precursor

#104 Tablesalt: RedisHash: Use Default
  tablesalt/lib/tablesalt/redis_hash/accessors.rb
  tablesalt/lib/tablesalt/redis_hash/default.rb
  tablesalt/lib/tablesalt/redis_hash/deletions.rb
  tablesalt/spec/tablesalt/redis_hash/accessors_spec.rb
  tablesalt/spec/tablesalt/redis_hash/deletions_spec.rb
Labels: Feature

#105 Tablesalt: RedisHash: Fix Default
  tablesalt/lib/tablesalt/redis_hash/default.rb
  tablesalt/spec/tablesalt/redis_hash/default_spec.rb
Labels: Correction

#106 Tablesalt: RedisHash: Set Default
  tablesalt/lib/tablesalt/redis_hash/core.rb
  tablesalt/lib/tablesalt/redis_hash/default.rb
  tablesalt/spec/support/shared_context/with_an_example_redis_hash.rb
  tablesalt/spec/tablesalt/redis_hash/comparisons_spec.rb
  tablesalt/spec/tablesalt/redis_hash/core_spec.rb
Labels: Feature

#107 Tablesalt: RedisHash: Converters
  tablesalt/lib/tablesalt/redis_hash/converters.rb
  tablesalt/lib/tablesalt/redis_hash/identity.rb
  tablesalt/lib/tablesalt/redis_hash/insertions.rb
  tablesalt/lib/tablesalt/redis_hash/predicates.rb
  tablesalt/lib/tablesalt/redis_hash_base.rb
  tablesalt/spec/tablesalt/redis_hash/converters_spec.rb
  tablesalt/spec/tablesalt/redis_hash/identity_spec.rb
  tablesalt/spec/tablesalt/redis_hash/insertions_spec.rb
  tablesalt/spec/tablesalt/redis_hash_base_spec.rb
Labels: Feature

#110 Tablesalt: RedisHash: Integration Test
  tablesalt/spec/integration/redis_hash_integration_spec.rb
  tablesalt/spec/integration/test_classes/redis_hash_spec.rb
  tablesalt/spec/support/test_classes/redis_hash.rb
Labels: Feature

#111 Tablesalt: RedisHash: Redis Adapter
  tablesalt/lib/tablesalt/redis_hash/adapter.rb
  tablesalt/lib/tablesalt/redis_hash/core.rb
  tablesalt/lib/tablesalt/redis_hash/default.rb
  tablesalt/lib/tablesalt/redis_hash_base.rb
  tablesalt/spec/support/shared_context/with_an_example_redis_hash.rb
  tablesalt/spec/tablesalt/redis_hash/adapter_spec.rb
  tablesalt/spec/tablesalt/redis_hash/core_spec.rb
  tablesalt/spec/tablesalt/redis_hash_base_spec.rb
Labels: Refactoring

#115 RedisHash: TTL
  redis_hash/lib/redis_hash/concerns/adapter.rb
  redis_hash/lib/redis_hash/concerns/core.rb
  redis_hash/spec/redis_hash/adapter_spec.rb
  redis_hash/spec/redis_hash/core_spec.rb
Labels: Feature

#116 RedisHash: Delegation Refactor
  redis_hash/lib/redis_hash/concerns/accessors.rb
  redis_hash/lib/redis_hash/concerns/adapter.rb
  redis_hash/lib/redis_hash/concerns/deletions.rb
  redis_hash/lib/redis_hash/concerns/identity.rb
  redis_hash/lib/redis_hash/concerns/insertions.rb
  redis_hash/lib/redis_hash/concerns/predicates.rb
  redis_hash/spec/redis_hash/accessors_spec.rb
  redis_hash/spec/redis_hash/adapter_spec.rb
  redis_hash/spec/redis_hash/deletions_spec.rb
  redis_hash/spec/redis_hash/identity_spec.rb
  redis_hash/spec/redis_hash/insertions_spec.rb
  redis_hash/spec/redis_hash/predicates_spec.rb
Labels: Refactoring

#117 RedisHash: Counters
  redis_hash/lib/redis_hash/base.rb
  redis_hash/lib/redis_hash/concerns/counters.rb
  redis_hash/spec/integration/example_redis_hash_integration_spec.rb
  redis_hash/spec/redis_hash/base_spec.rb
  redis_hash/spec/redis_hash/counters_spec.rb
Labels: Feature

#118 RedisHash: setnx
  redis_hash/lib/redis_hash.rb
  redis_hash/lib/redis_hash/concerns/insertions.rb
  redis_hash/spec/redis_hash/insertions_spec.rb
  redis_hash/spec/redis_hash_spec.rb
Labels: Feature

#119 RedisHash: Callbacks
  Gemfile.lock
  redis_hash/lib/redis_hash.rb
  redis_hash/lib/redis_hash/base.rb
  redis_hash/lib/redis_hash/concerns/callbacks.rb
  redis_hash/lib/redis_hash/concerns/deletions.rb
  redis_hash/lib/redis_hash/concerns/insertions.rb
  redis_hash/redis_hash.gemspec
  redis_hash/spec/integration/example_redis_hash_integration_spec.rb
  redis_hash/spec/redis_hash/base_spec.rb
  redis_hash/spec/redis_hash/callbacks_spec.rb
  redis_hash/spec/redis_hash/deletions_spec.rb
  redis_hash/spec/redis_hash/insertions_spec.rb
Labels: Feature

#120 RedisHash: Expiration
  redis_hash/lib/redis_hash/base.rb
  redis_hash/lib/redis_hash/concerns/expiration.rb
  redis_hash/spec/integration/example_redis_hash_integration_spec.rb
  redis_hash/spec/redis_hash/base_spec.rb
  redis_hash/spec/redis_hash/expiration_spec.rb
  redis_hash/spec/support/shared_context/with_an_example_redis_hash.rb
Labels: Feature

#122 Tablesalt: HashModel
  Gemfile.lock
  shared/spec_helper.rb
  tablesalt/lib/tablesalt.rb
  tablesalt/lib/tablesalt/hash_model.rb
  tablesalt/spec/integration/processor_hash_model_spec.rb
  tablesalt/spec/integration/task_hash_model_spec.rb
  tablesalt/spec/spec_helper.rb
  tablesalt/spec/support/shared_examples/a_hash_model_reader.rb
  tablesalt/spec/support/shared_examples/a_hash_model_writer.rb
  tablesalt/spec/support/shared_examples/a_task_hash_model.rb
  tablesalt/spec/support/test_classes/hash_model.rb
  tablesalt/tablesalt.gemspec
Labels: Feature

#123 Release 0.9.2
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  instructor/CHANGELOG.md
  instructor/lib/instructor/version.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#124 Release 0.9.2
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  instructor/CHANGELOG.md
  instructor/lib/instructor/version.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  shared/spec_helper.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt.rb
  tablesalt/lib/tablesalt/hash_model.rb
  tablesalt/lib/tablesalt/version.rb
  tablesalt/spec/integration/processor_hash_model_spec.rb
  tablesalt/spec/integration/task_hash_model_spec.rb
  tablesalt/spec/spec_helper.rb
  tablesalt/spec/support/shared_examples/a_hash_model_reader.rb
  tablesalt/spec/support/shared_examples/a_hash_model_writer.rb
  tablesalt/spec/support/shared_examples/a_task_hash_model.rb
  tablesalt/spec/support/test_classes/hash_model.rb
  tablesalt/tablesalt.gemspec
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#129 Release 0.9.4
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  instructor/CHANGELOG.md
  instructor/lib/instructor/version.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/array_index.rb
  tablesalt/lib/tablesalt/version.rb
  tablesalt/spec/tablesalt/array_index_spec.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#130 fix ArrayIndex#freeze
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/array_index.rb
  tablesalt/spec/tablesalt/array_index_spec.rb
Labels: Correction

#131 Release 0.9.5
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  instructor/CHANGELOG.md
  instructor/lib/instructor/version.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/array_index.rb
  tablesalt/lib/tablesalt/version.rb
  tablesalt/spec/tablesalt/array_index_spec.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#132 Tablesalt: HashModel: Rename #hash to #data
  tablesalt/lib/tablesalt/hash_model.rb
  tablesalt/spec/support/test_classes/hash_model.rb
Labels: Correction

#133 Tablesalt: HashModel: Predicates
  tablesalt/lib/tablesalt/hash_model.rb
  tablesalt/spec/integration/processor_hash_model_spec.rb
  tablesalt/spec/integration/task_hash_model_spec.rb
  tablesalt/spec/spec_helper.rb
  tablesalt/spec/support/shared_examples/a_hash_model_predicate.rb
  tablesalt/spec/support/shared_examples/a_hash_model_reader.rb
  tablesalt/spec/support/shared_examples/a_hash_model_writer.rb
  tablesalt/spec/support/shared_examples/a_task_hash_model.rb
Labels: Feature

#135 Tablesalt: HashModel: SpecHelper
  shared/spec_helper.rb
  tablesalt/lib/tablesalt/custom_matchers.rb
  tablesalt/lib/tablesalt/custom_matchers/define_field.rb
  tablesalt/lib/tablesalt/spec_helper.rb
  tablesalt/spec/integration/processor_hash_model_spec.rb
  tablesalt/spec/integration/task_hash_model_spec.rb
Labels: Feature

#136 Spicerack: spec_helper
  lib/spicerack/spec_helper.rb
  shared/spec_helper.rb
  technologic/spec/technologic_spec.rb
Labels: Feature

#134 update index on array modification
  CHANGELOG.md
  lib/spicerack.rb
  lib/spicerack/array_index.rb
  spec/spicerack/array_index_spec.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt.rb
Labels: Feature

#137 Spicerack: HashModel
  lib/spicerack.rb
  lib/spicerack/custom_matchers.rb
  lib/spicerack/custom_matchers/define_field.rb
  lib/spicerack/hash_model.rb
  lib/spicerack/spec_helper.rb
  spec/integration/processor_hash_model_spec.rb
  spec/integration/task_hash_model_spec.rb
  spec/support/shared_examples/a_hash_model_predicate.rb
  spec/support/shared_examples/a_hash_model_reader.rb
  spec/support/shared_examples/a_hash_model_writer.rb
  spec/support/shared_examples/a_task_hash_model.rb
  spec/support/test_classes/hash_model.rb
  tablesalt/lib/tablesalt.rb
  tablesalt/lib/tablesalt/spec_helper.rb
  tablesalt/spec/spec_helper.rb
Labels: Feature

#138 RedisHash: More Redis Methods
  redis_hash/lib/redis_hash/concerns/adapter.rb
  redis_hash/lib/redis_hash/concerns/expiration.rb
  redis_hash/spec/redis_hash/adapter_spec.rb
  redis_hash/spec/redis_hash/expiration_spec.rb
Labels: Feature

#139 RedisHash: Schema
  instructor/lib/instructor.rb
  redis_hash/lib/redis_hash.rb
  redis_hash/lib/redis_hash/base.rb
  redis_hash/lib/redis_hash/concerns/schema.rb
  redis_hash/spec/redis_hash/base_spec.rb
  redis_hash/spec/redis_hash/schema_spec.rb
Labels: Precursor

#141 RedisHash: Schema Enforcement
  redis_hash/lib/redis_hash/concerns/insertions.rb
  redis_hash/spec/redis_hash/insertions_spec.rb
  redis_hash/spec/redis_hash/schema_spec.rb
  redis_hash/spec/support/shared_context/with_an_example_redis_hash.rb
Labels: Feature

#142 Tablesalt: StringableObject
  tablesalt/lib/tablesalt.rb
  tablesalt/lib/tablesalt/stringable_object.rb
  tablesalt/spec/tablesalt/stringable_object_spec.rb
Labels: Precursor

#143 Instructor: StringableObject
  instructor/lib/instructor.rb
  instructor/lib/instructor/base.rb
  instructor/lib/instructor/concerns/attributes.rb
  instructor/lib/instructor/concerns/string.rb
  instructor/spec/instructor/attributes_spec.rb
  instructor/spec/instructor/base_spec.rb
  instructor/spec/instructor/string_spec.rb
  instructor/spec/integration/bottles_on_the_wall_spec.rb
Labels: Refactoring

#144 Release 0.9.6
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  instructor/CHANGELOG.md
  instructor/lib/instructor/version.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#145 Release 0.9.6
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  instructor/CHANGELOG.md
  instructor/lib/instructor.rb
  instructor/lib/instructor/base.rb
  instructor/lib/instructor/concerns/attributes.rb
  instructor/lib/instructor/version.rb
  instructor/spec/instructor/attributes_spec.rb
  instructor/spec/instructor/base_spec.rb
  instructor/spec/instructor/string_spec.rb
  instructor/spec/integration/bottles_on_the_wall_spec.rb
  lib/spicerack.rb
  lib/spicerack/array_index.rb
  lib/spicerack/custom_matchers.rb
  lib/spicerack/custom_matchers/define_field.rb
  lib/spicerack/hash_model.rb
  lib/spicerack/spec_helper.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash.rb
  redis_hash/lib/redis_hash/base.rb
  redis_hash/lib/redis_hash/concerns/adapter.rb
  redis_hash/lib/redis_hash/concerns/expiration.rb
  redis_hash/lib/redis_hash/concerns/insertions.rb
  redis_hash/lib/redis_hash/concerns/schema.rb
  redis_hash/lib/redis_hash/version.rb
  redis_hash/spec/redis_hash/adapter_spec.rb
  redis_hash/spec/redis_hash/base_spec.rb
  redis_hash/spec/redis_hash/expiration_spec.rb
  redis_hash/spec/redis_hash/insertions_spec.rb
  redis_hash/spec/redis_hash/schema_spec.rb
  redis_hash/spec/support/shared_context/with_an_example_redis_hash.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  shared/spec_helper.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spec/integration/processor_hash_model_spec.rb
  spec/integration/task_hash_model_spec.rb
  spec/spicerack/array_index_spec.rb
  spec/support/shared_examples/a_hash_model_predicate.rb
  spec/support/shared_examples/a_hash_model_reader.rb
  spec/support/shared_examples/a_hash_model_writer.rb
  spec/support/shared_examples/a_task_hash_model.rb
  spec/support/test_classes/hash_model.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt.rb
  tablesalt/lib/tablesalt/stringable_object.rb
  tablesalt/lib/tablesalt/version.rb
  tablesalt/spec/spec_helper.rb
  tablesalt/spec/tablesalt/stringable_object_spec.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
  technologic/spec/technologic_spec.rb
Labels: Release

#146 Spec Helper Cleanup
  lib/spicerack/custom_matchers/define_field.rb
  lib/spicerack/spec_helper.rb
  redis_hash/lib/redis_hash/custom_matchers.rb
  redis_hash/lib/redis_hash/custom_matchers/allow_key.rb
  redis_hash/lib/redis_hash/spec_helper.rb
  redis_hash/spec/integration/test_classes/schema_redis_hash_spec.rb
  redis_hash/spec/support/test_classes/schema_redis_hash.rb
Labels: Correction, Feature

#147 Gem Yanker
  Rakefile
Labels: Feature

#148 Release 0.10.0
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  instructor/CHANGELOG.md
  instructor/lib/instructor/version.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#149 Release 0.10.0
  CHANGELOG.md
  Gemfile.lock
  Rakefile
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  instructor/CHANGELOG.md
  instructor/lib/instructor/version.rb
  lib/spicerack/custom_matchers/define_field.rb
  lib/spicerack/spec_helper.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/custom_matchers.rb
  redis_hash/lib/redis_hash/custom_matchers/allow_key.rb
  redis_hash/lib/redis_hash/spec_helper.rb
  redis_hash/lib/redis_hash/version.rb
  redis_hash/spec/integration/test_classes/schema_redis_hash_spec.rb
  redis_hash/spec/support/test_classes/schema_redis_hash.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#150 Spicerack: RedisModel
  lib/spicerack.rb
  lib/spicerack/redis_model.rb
  spec/integration/processor_redis_model_spec.rb
  spec/integration/task_redis_model_spec.rb
  spec/support/test_classes/redis_model.rb
Labels: Feature

#151 Release 0.10.1
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  instructor/CHANGELOG.md
  instructor/lib/instructor/version.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#152 Release 0.10.1
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  instructor/CHANGELOG.md
  instructor/lib/instructor/version.rb
  lib/spicerack.rb
  lib/spicerack/redis_model.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spec/integration/processor_redis_model_spec.rb
  spec/integration/task_redis_model_spec.rb
  spec/support/test_classes/redis_model.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#153 Tablesalt: DSL: Defaults
  Gemfile.lock
  instructor/instructor.gemspec
  instructor/lib/instructor/base.rb
  instructor/lib/instructor/concerns/defaults.rb
  instructor/spec/instructor/base_spec.rb
  instructor/spec/instructor/defaults_spec.rb
  instructor/spec/instructor/options_spec.rb
  tablesalt/lib/tablesalt.rb
  tablesalt/lib/tablesalt/dsl/defaults.rb
  tablesalt/spec/tablesalt/dsl/defaults/value_spec.rb
  tablesalt/spec/tablesalt/dsl/defaults_spec.rb
Labels: Refactoring

#154 Release 0.10.2
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  instructor/CHANGELOG.md
  instructor/instructor.gemspec
  instructor/lib/instructor/base.rb
  instructor/lib/instructor/concerns/defaults.rb
  instructor/lib/instructor/version.rb
  instructor/spec/instructor/base_spec.rb
  instructor/spec/instructor/defaults_spec.rb
  instructor/spec/instructor/options_spec.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt.rb
  tablesalt/lib/tablesalt/dsl/defaults.rb
  tablesalt/lib/tablesalt/version.rb
  tablesalt/spec/tablesalt/dsl/defaults/value_spec.rb
  tablesalt/spec/tablesalt/dsl/defaults_spec.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#159 RootObject
  root_object/lib/root_object.rb
  root_object/lib/root_object/base.rb
  root_object/spec/root_object/base_spec.rb
Labels: Feature

#160 Ascriptor::Base
  Gemfile.lock
  ascriptor/ascriptor.gemspec
  ascriptor/lib/ascriptor.rb
  ascriptor/lib/ascriptor/base.rb
  ascriptor/spec/ascriptor/base_spec.rb
Labels: Precursor

#161 Consolidate RootObject
  CHANGELOG.md
  Gemfile.lock
  README.md
  Rakefile
  lib/spicerack.rb
  lib/spicerack/root_object.rb
  root_object/.rspec
  root_object/CHANGELOG.md
  root_object/LICENSE.txt
  root_object/README.md
  root_object/Rakefile
  root_object/bin/console
  root_object/bin/setup
  root_object/lib/root_object.rb
  root_object/lib/root_object/version.rb
  root_object/root_object.gemspec
  root_object/spec/root_object_spec.rb
  root_object/spec/spec_helper.rb
  spec/spicerack/root_object_spec.rb
  spicerack.gemspec
Labels: Refactoring

#162 Consolidate Ascriptor
  CHANGELOG.md
  Gemfile.lock
  Rakefile
  ascriptor/.rspec
  ascriptor/CHANGELOG.md
  ascriptor/LICENSE.txt
  ascriptor/README.md
  ascriptor/Rakefile
  ascriptor/ascriptor.gemspec
  ascriptor/bin/console
  ascriptor/bin/setup
  ascriptor/lib/ascriptor.rb
  ascriptor/lib/ascriptor/base.rb
  ascriptor/lib/ascriptor/version.rb
  ascriptor/spec/ascriptor/base_spec.rb
  ascriptor/spec/ascriptor_spec.rb
  ascriptor/spec/spec_helper.rb
  lib/spicerack.rb
  lib/spicerack/ascriptor.rb
  spec/spicerack/ascriptor_spec.rb
  spicerack.gemspec
Labels: Refactoring

#163 Consolidate Instructor
  CHANGELOG.md
  Gemfile.lock
  Rakefile
  instructor/.rspec
  instructor/CHANGELOG.md
  instructor/LICENSE.txt
  instructor/README.md
  instructor/Rakefile
  instructor/bin/console
  instructor/bin/setup
  instructor/instructor.gemspec
  instructor/lib/instructor.rb
  instructor/lib/instructor/spec_helper.rb
  instructor/lib/instructor/version.rb
  instructor/spec/instructor_spec.rb
  instructor/spec/spec_helper.rb
  lib/spicerack.rb
  lib/spicerack/ascriptor_base.rb
  lib/spicerack/custom_matchers.rb
  lib/spicerack/instructor/arguments.rb
  lib/spicerack/instructor/attributes.rb
  lib/spicerack/instructor/callbacks.rb
  lib/spicerack/instructor/core.rb
  lib/spicerack/instructor/options.rb
  lib/spicerack/instructor_base.rb
  lib/spicerack/rspec/custom_matchers.rb
  lib/spicerack/rspec/custom_matchers/define_argument.rb
  lib/spicerack/rspec/custom_matchers/define_attribute.rb
  lib/spicerack/rspec/custom_matchers/define_field.rb
  lib/spicerack/rspec/custom_matchers/define_option.rb
  lib/spicerack/rspec/shared_examples.rb
  lib/spicerack/rspec/shared_examples/an_instructor_with_a_class_collection_attribute.rb
  lib/spicerack/rspec/shoulda_matcher_helper.rb
  lib/spicerack/spec_helper.rb
  spec/spicerack/ascriptor_base_spec.rb
  spec/spicerack/example_instructor_spec.rb
  spec/spicerack/hash_model/processor_hash_model_spec.rb
  spec/spicerack/hash_model/task_hash_model_spec.rb
  spec/spicerack/instructor/arguments_spec.rb
  spec/spicerack/instructor/attributes_spec.rb
  spec/spicerack/instructor/callbacks_spec.rb
  spec/spicerack/instructor/core_spec.rb
  spec/spicerack/instructor/options_spec.rb
  spec/spicerack/instructor_base_spec.rb
  spec/spicerack/redis_model/processor_redis_model_spec.rb
  spec/spicerack/redis_model/task_redis_model_spec.rb
  spec/support/shared_context/with_an_example_instructor.rb
  spec/support/shared_examples/a_class_with_attributes_having_default_values.rb
  spec/support/test_classes/instructor.rb
  spicerack.gemspec
Labels: Refactoring

#164 Integration Spec Cleanup
  spec/integration/example_hash_model_spec.rb
  spec/integration/example_instructor_spec.rb
  spec/integration/example_redis_model_spec.rb
  spec/spicerack/hash_model/task_hash_model_spec.rb
  spec/spicerack/redis_model/processor_redis_model_spec.rb
  spec/support/shared_examples/a_task_hash_model.rb
  spec/support/test_classes/example_hash_model.rb
  spec/support/test_classes/example_instructor.rb
  spec/support/test_classes/example_redis_model.rb
Labels: Refactoring

#165 Move Versioned Spicerack Gem
  CHANGELOG.md
  rspice/CHANGELOG.md
  rspice/README.md
  rspice/lib/rspice/shared_examples.rb
  shared/shared_examples/a_versioned_spicerack_gem.rb
  shared/spec_helper.rb
Labels: Correction, Refactoring

#166 Instructor based on Ascriptor
  lib/spicerack/ascriptor_base.rb
  lib/spicerack/instructor/callbacks.rb
  lib/spicerack/instructor/core.rb
  lib/spicerack/instructor_base.rb
  rspice/CHANGELOG.md
  rspice/README.md
  rspice/lib/rspice/shared_context.rb
  rspice/lib/rspice/shared_context/with_class_callbacks.rb
  spec/spicerack/instructor/arguments_spec.rb
  spec/spicerack/instructor/attributes_spec.rb
  spec/spicerack/instructor/callbacks_spec.rb
  spec/spicerack/instructor/core_spec.rb
  spec/spicerack/instructor/options_spec.rb
  spec/spicerack/instructor_base_spec.rb
  spec/support/shared_context/with_an_example_instructor.rb
Labels: Refactoring

#167 Move Tablesalt::Dsl::Defaults to Ascriptor
  CHANGELOG.md
  lib/spicerack.rb
  lib/spicerack/ascriptor/defaults.rb
  lib/spicerack/ascriptor_base.rb
  lib/spicerack/instructor_base.rb
  spec/spicerack/ascriptor/defaults/value_spec.rb
  spec/spicerack/ascriptor/defaults_spec.rb
  spec/spicerack/ascriptor_base_spec.rb
  spec/spicerack/instructor/options_spec.rb
  spec/spicerack/instructor_base_spec.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt.rb
Labels: Refactoring

#168 Move Instructor::Attributes to Ascriptor
  lib/spicerack/ascriptor/attributes.rb
  lib/spicerack/ascriptor_base.rb
  lib/spicerack/instructor/attributes.rb
  lib/spicerack/instructor_base.rb
  spec/spicerack/ascriptor/attributes_spec.rb
  spec/spicerack/ascriptor_base_spec.rb
  spec/spicerack/instructor_base_spec.rb
  spec/support/shared_context/with_an_example_instructor.rb
Labels: Feature

#169 InputObjectBase
  lib/spicerack.rb
  lib/spicerack/input_object_base.rb
  spec/spicerack/input_object_base_spec.rb
Labels: Precursor

#170 AttributeObject
  CHANGELOG.md
  lib/spicerack.rb
  lib/spicerack/ascriptor_base.rb
  lib/spicerack/attribute_object.rb
  lib/spicerack/input_object_base.rb
  lib/spicerack/instructor_base.rb
  lib/spicerack/objects/attributes.rb
  lib/spicerack/objects/defaults.rb
  spec/spicerack/ascriptor_base_spec.rb
  spec/spicerack/attribute_object_spec.rb
  spec/spicerack/input_object_base_spec.rb
  spec/spicerack/instructor_base_spec.rb
  spec/spicerack/objects/attributes_spec.rb
  spec/spicerack/objects/defaults/value_spec.rb
  spec/spicerack/objects/defaults_spec.rb
  spec/support/shared_context/with_an_example_instructor.rb
Labels: Refactoring

#171 InputObject
  lib/spicerack.rb
  lib/spicerack/input_object.rb
  lib/spicerack/input_object_base.rb
  lib/spicerack/instructor/arguments.rb
  lib/spicerack/instructor/core.rb
  lib/spicerack/instructor/options.rb
  lib/spicerack/instructor_base.rb
  lib/spicerack/objects/arguments.rb
  lib/spicerack/objects/options.rb
  lib/spicerack/rspec/shared_examples.rb
  lib/spicerack/rspec/shared_examples/an_input_object_with_a_class_collection_attribute.rb
  spec/spicerack/input_object_base_spec.rb
  spec/spicerack/input_object_spec.rb
  spec/spicerack/instructor/core_spec.rb
  spec/spicerack/instructor/options_spec.rb
  spec/spicerack/instructor_base_spec.rb
  spec/spicerack/objects/arguments_spec.rb
  spec/spicerack/objects/options_spec.rb
  spec/support/shared_context/with_an_example_input_object.rb
  spec/support/shared_context/with_an_example_instructor.rb
Labels: Refactoring

#172 InputModel
  CHANGELOG.md
  README.md
  lib/spicerack.rb
  lib/spicerack/input_model.rb
  lib/spicerack/rspec/custom_matchers/define_argument.rb
  lib/spicerack/rspec/custom_matchers/define_attribute.rb
  lib/spicerack/rspec/custom_matchers/define_option.rb
  lib/spicerack/rspec/shoulda_matcher_helper.rb
  spec/integration/example_input_model_spec.rb
  spec/spicerack/input_model_spec.rb
  spec/spicerack/objects/attributes_spec.rb
  spec/support/shared_context/with_an_example_instructor.rb
  spec/support/test_classes/example_input_model.rb
Labels: Refactoring

#173 Cleanup Example Input Object
  spec/support/shared_context/with_an_example_input_object.rb
Labels: Maintenance

#174 Release 0.13.0
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#176 Define Callbacks with Handler
  CHANGELOG.md
  lib/spicerack/root_object.rb
  rspice/CHANGELOG.md
  rspice/README.md
  rspice/lib/rspice/shared_examples.rb
  rspice/lib/rspice/shared_examples/a_handler_for_the_callback.rb
  spec/spicerack/root_object_spec.rb
Labels: Feature

#177 Release 0.13.1
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#178 Release 0.13.1
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  lib/spicerack/root_object.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/README.md
  rspice/lib/rspice/shared_examples.rb
  rspice/lib/rspice/shared_examples/a_handler_for_the_callback.rb
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spec/spicerack/root_object_spec.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#179 Spec Helper Cleanup
  lib/spicerack/spec_helper.rb
  redis_hash/lib/redis_hash/rspec/custom_matchers.rb
  redis_hash/lib/redis_hash/rspec/custom_matchers/allow_key.rb
  redis_hash/lib/redis_hash/spec_helper.rb
  technologic/lib/technologic/rspec/shared_examples.rb
  technologic/lib/technologic/rspec/shared_examples/a_debug_event_is_logged.rb
  technologic/lib/technologic/rspec/shared_examples/a_fatal_event_is_logged.rb
  technologic/lib/technologic/rspec/shared_examples/a_logged_event_with_severity.rb
  technologic/lib/technologic/rspec/shared_examples/a_surveiled_event.rb
  technologic/lib/technologic/rspec/shared_examples/a_warn_event_is_logged.rb
  technologic/lib/technologic/rspec/shared_examples/an_error_event_is_logged.rb
  technologic/lib/technologic/rspec/shared_examples/an_info_event_is_logged.rb
  technologic/lib/technologic/rspec/shared_examples/an_instrumented_error_exception.rb
  technologic/lib/technologic/rspec/shared_examples/an_instrumented_exception_with_severity.rb
  technologic/lib/technologic/rspec/shared_examples/an_instrumented_fatal_exception.rb
  technologic/lib/technologic/spec_helper.rb
Labels: Correction

#180 Release 0.13.2
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#181 Release 0.13.2
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  lib/spicerack/spec_helper.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/rspec/custom_matchers.rb
  redis_hash/lib/redis_hash/rspec/custom_matchers/allow_key.rb
  redis_hash/lib/redis_hash/spec_helper.rb
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/rspec/shared_examples.rb
  technologic/lib/technologic/rspec/shared_examples/a_debug_event_is_logged.rb
  technologic/lib/technologic/rspec/shared_examples/a_fatal_event_is_logged.rb
  technologic/lib/technologic/rspec/shared_examples/a_logged_event_with_severity.rb
  technologic/lib/technologic/rspec/shared_examples/a_surveiled_event.rb
  technologic/lib/technologic/rspec/shared_examples/a_warn_event_is_logged.rb
  technologic/lib/technologic/rspec/shared_examples/an_error_event_is_logged.rb
  technologic/lib/technologic/rspec/shared_examples/an_info_event_is_logged.rb
  technologic/lib/technologic/rspec/shared_examples/an_instrumented_error_exception.rb
  technologic/lib/technologic/rspec/shared_examples/an_instrumented_exception_with_severity.rb
  technologic/lib/technologic/rspec/shared_examples/an_instrumented_fatal_exception.rb
  technologic/lib/technologic/spec_helper.rb
  technologic/lib/technologic/version.rb
Labels: Release
