Repository Freshly/spicerack, pull requests merged in 2019-08, with the labels that each got.

#205 make class pass a bit more flexible
  rspice/lib/rspice/shared_examples/a_class_pass_method.rb
Labels: Correction

#212 Collectible/CollectionBase
  Gemfile.lock
  collectible/collectible.gemspec
  collectible/lib/collectible.rb
  collectible/lib/collectible/collection_base.rb
  collectible/spec/collectible/collection_base_spec.rb
  collectible/spec/collectible_spec.rb
  lib/spicerack.rb
  rspice/lib/rspice/rspec_configuration.rb
Labels: Precursor

#213 Tablesalt/UseHashForEquality
  CHANGELOG.md
  Gemfile.lock
  around_the_world/CHANGELOG.md
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/base.rb
  redis_hash/lib/redis_hash/concerns/comparisons.rb
  redis_hash/redis_hash.gemspec
  redis_hash/spec/redis_hash/comparisons_spec.rb
  redis_hash/spec/support/shared_context/with_an_example_redis_hash.rb
  rspice/CHANGELOG.md
  short_circu_it/CHANGELOG.md
  spicerack-styleguide/CHANGELOG.md
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt.rb
  tablesalt/lib/tablesalt/uses_hash_for_equality.rb
  tablesalt/spec/tablesalt/uses_hash_for_equality_spec.rb
  technologic/CHANGELOG.md
Labels: Correction, Feature, Refactoring

#214 Collectible/Collection/Core
  collectible/CHANGELOG.md
  collectible/collectible.gemspec
  collectible/lib/collectible.rb
  collectible/lib/collectible/collection/core.rb
  collectible/lib/collectible/collection_base.rb
  collectible/spec/collectible/collection/core_spec.rb
  collectible/spec/collectible/collection_base_spec.rb
  collectible/spec/spec_helper.rb
  collectible/spec/support/shared_context/with_an_example_collection.rb
Labels: Feature

#215 EnsuresItemEligibility
  collectible/CHANGELOG.md
  collectible/lib/collectible.rb
  collectible/lib/collectible/collection/ensures_item_eligibility.rb
  collectible/lib/collectible/collection_base.rb
  collectible/spec/collectible/collection/ensures_item_eligibility_spec.rb
  collectible/spec/collectible/collection_base_spec.rb
Labels: Feature

#216 WrapsCollectionMethods
  collectible/lib/collectible.rb
  collectible/lib/collectible/collection/ensures_item_eligibility.rb
  collectible/lib/collectible/collection/wraps_collection_methods.rb
  collectible/lib/collectible/collection_base.rb
  collectible/spec/collectible/collection/wraps_collection_methods_spec.rb
  collectible/spec/collectible/collection_base_spec.rb
Labels: Feature

#217 MaintainSortOrder
  collectible/lib/collectible.rb
  collectible/lib/collectible/collection/maintain_sort_order.rb
  collectible/lib/collectible/collection/wraps_collection_methods.rb
  collectible/lib/collectible/collection_base.rb
  collectible/spec/collectible/collection/maintain_sort_order_spec.rb
  collectible/spec/collectible/collection_base_spec.rb
  collectible/spec/collectible_spec.rb
Labels: Feature

#218 Collectible: Collection: Finder
  Gemfile.lock
  collectible/collectible.gemspec
  collectible/lib/collectible.rb
  collectible/lib/collectible/collection/finder.rb
  collectible/lib/collectible/collection/maintain_sort_order.rb
  collectible/lib/collectible/collection_base.rb
  collectible/spec/collectible/collection/finder_spec.rb
  collectible/spec/collectible/collection/maintain_sort_order_spec.rb
  collectible/spec/collectible/collection_base_spec.rb
Labels: Feature

#219 Release 0.15.1
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/lib/around_the_world/version.rb
  collectible/lib/collectible/version.rb
  lib/spicerack/version.rb
  redis_hash/lib/redis_hash/version.rb
  rspice/lib/rspice/version.rb
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/lib/tablesalt/version.rb
  technologic/lib/technologic/version.rb
Labels: Release

#220 Release 0.15.1
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  collectible/CHANGELOG.md
  collectible/collectible.gemspec
  collectible/lib/collectible.rb
  collectible/lib/collectible/collection/core.rb
  collectible/lib/collectible/collection/ensures_item_eligibility.rb
  collectible/lib/collectible/collection/finder.rb
  collectible/lib/collectible/collection/maintain_sort_order.rb
  collectible/lib/collectible/collection/wraps_collection_methods.rb
  collectible/lib/collectible/collection_base.rb
  collectible/lib/collectible/version.rb
  collectible/spec/collectible/collection/core_spec.rb
  collectible/spec/collectible/collection/ensures_item_eligibility_spec.rb
  collectible/spec/collectible/collection/finder_spec.rb
  collectible/spec/collectible/collection/maintain_sort_order_spec.rb
  collectible/spec/collectible/collection/wraps_collection_methods_spec.rb
  collectible/spec/collectible/collection_base_spec.rb
  collectible/spec/collectible_spec.rb
  collectible/spec/spec_helper.rb
  collectible/spec/support/shared_context/with_an_example_collection.rb
  lib/spicerack.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/base.rb
  redis_hash/lib/redis_hash/concerns/comparisons.rb
  redis_hash/lib/redis_hash/version.rb
  redis_hash/redis_hash.gemspec
  redis_hash/spec/redis_hash/comparisons_spec.rb
  redis_hash/spec/support/shared_context/with_an_example_redis_hash.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/rspec_configuration.rb
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt.rb
  tablesalt/lib/tablesalt/uses_hash_for_equality.rb
  tablesalt/lib/tablesalt/version.rb
  tablesalt/spec/tablesalt/uses_hash_for_equality_spec.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#223 Upgrade rubocop
  Gemfile.lock
  spicerack-styleguide/rubocop.yml
  spicerack-styleguide/spicerack-styleguide.gemspec
Labels: Correction, Maintenance

#224 Release 0.15.2
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  collectible/CHANGELOG.md
  collectible/lib/collectible/version.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  spicerack-styleguide/rubocop.yml
  spicerack-styleguide/spicerack-styleguide.gemspec
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#225 Rubocop & codeclimate config updates
  .codeclimate.yml
  .rubocop.yml
Labels: Maintenance

#238 Facet::Record
  facet/lib/facet.rb
  facet/lib/facet/base.rb
  facet/lib/facet/concerns/record.rb
  facet/spec/facet/base_spec.rb
  facet/spec/facet/record_spec.rb
  facet/spec/support/shared_context/with_an_example_facet.rb
Labels: Feature

#239 Facet::Cache
  Gemfile.lock
  facet/facet.gemspec
  facet/lib/facet.rb
  facet/lib/facet/base.rb
  facet/lib/facet/concerns/cache.rb
  facet/lib/facet/concerns/record.rb
  facet/spec/facet/base_spec.rb
  facet/spec/facet/cache_spec.rb
  facet/spec/facet/record_spec.rb
Labels: Feature

#240 Facet::Collection
  facet/lib/facet/base.rb
  facet/lib/facet/concerns/collection.rb
  facet/lib/facet/concerns/core.rb
  facet/lib/facet/concerns/record.rb
  facet/spec/facet/base_spec.rb
  facet/spec/facet/collection_spec.rb
  facet/spec/facet/core_spec.rb
  facet/spec/facet/record_spec.rb
Labels: Feature

#241 Facet::Paginate
  facet/lib/facet/base.rb
  facet/lib/facet/concerns/core.rb
  facet/lib/facet/concerns/paginate.rb
  facet/spec/facet/base_spec.rb
  facet/spec/facet/core_spec.rb
  facet/spec/facet/paginate_spec.rb
Labels: Feature

#242 Facet Integration Testing
  Gemfile.lock
  facet/lib/facet/concerns/collection.rb
  facet/lib/facet/concerns/core.rb
  facet/lib/facet/concerns/paginate.rb
  facet/spec/facet/core_spec.rb
  facet/spec/facet/paginate_spec.rb
  facet/spec/integration/bottle_facet_integration_spec.rb
  facet/spec/spec_helper.rb
  facet/spec/support/shared_context/with_a_bottles_active_record.rb
  facet/spec/support/shared_context/with_an_example_facet.rb
  facet/spec/support/shared_context/with_example_bottles.rb
  facet/spec/support/test_classes/bottle.rb
  facet/spec/support/test_classes/bottle_facet.rb
  facet/spec/test_classes/bottle_facet_spec.rb
  facet/spec/test_classes/bottle_spec.rb
  shared/spec_helper.rb
  spicerack.gemspec
Labels: Feature

#243 Release 0.16.2
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  collectible/CHANGELOG.md
  collectible/lib/collectible/version.rb
  facet/CHANGELOG.md
  facet/facet.gemspec
  facet/lib/facet.rb
  facet/lib/facet/base.rb
  facet/lib/facet/concerns/cache.rb
  facet/lib/facet/concerns/collection.rb
  facet/lib/facet/concerns/core.rb
  facet/lib/facet/concerns/filter.rb
  facet/lib/facet/concerns/paginate.rb
  facet/lib/facet/concerns/record.rb
  facet/lib/facet/concerns/sort.rb
  facet/lib/facet/version.rb
  facet/spec/facet/base_spec.rb
  facet/spec/facet/cache_spec.rb
  facet/spec/facet/collection_spec.rb
  facet/spec/facet/core_spec.rb
  facet/spec/facet/filter_spec.rb
  facet/spec/facet/paginate_spec.rb
  facet/spec/facet/record_spec.rb
  facet/spec/facet/sort_spec.rb
  facet/spec/integration/bottle_facet_integration_spec.rb
  facet/spec/spec_helper.rb
  facet/spec/support/shared_context/with_a_bottles_active_record.rb
  facet/spec/support/shared_context/with_an_example_facet.rb
  facet/spec/support/shared_context/with_example_bottles.rb
  facet/spec/support/test_classes/bottle.rb
  facet/spec/support/test_classes/bottle_facet.rb
  facet/spec/test_classes/bottle_facet_spec.rb
  facet/spec/test_classes/bottle_spec.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  shared/spec_helper.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  spicerack.gemspec
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release
