Repository Freshly/spicerack, pull requests merged in 2019-11, with the labels that each got.

#268 don't break ruby constant lookup
  lib/spicerack/configurable/config_object.rb
Labels: Correction

#269 Release 0.17.4
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  collectible/CHANGELOG.md
  collectible/lib/collectible/version.rb
  facet/CHANGELOG.md
  facet/lib/facet/version.rb
  lib/spicerack/configurable/config_object.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#282 fix undefined local variable, add coverage
  lib/spicerack/configurable/reader.rb
  spec/spicerack/configurable/reader_spec.rb
Labels: Correction

#294 Adds a missing include
  lib/spicerack.rb
Labels: Correction

#295 Release 0.19.1
  .gitignore
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  collectible/CHANGELOG.md
  collectible/lib/collectible/version.rb
  conjunction/CHANGELOG.md
  conjunction/lib/conjunction/version.rb
  facet/CHANGELOG.md
  facet/lib/facet/version.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  spicery/CHANGELOG.md
  spicery/lib/spicery/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#297 Wrap class methods in AroundTheWorld
  around_the_world/lib/around_the_world.rb
  around_the_world/spec/integration/example_classes/example_called_class.rb
  around_the_world/spec/integration/example_wrapped_class_spec.rb
Labels: Feature

#296 Release 0.19.1 (actual)
  .gitignore
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world.rb
  around_the_world/lib/around_the_world/version.rb
  around_the_world/spec/integration/example_classes/example_called_class.rb
  around_the_world/spec/integration/example_wrapped_class_spec.rb
  collectible/CHANGELOG.md
  collectible/lib/collectible/version.rb
  conjunction/CHANGELOG.md
  conjunction/lib/conjunction/version.rb
  facet/CHANGELOG.md
  facet/lib/facet/version.rb
  lib/spicerack.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  spicery/CHANGELOG.md
  spicery/lib/spicery/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release
