Repository Freshly/spicerack, pull requests merged in 2019-10, with the labels that each got.

#200 [WIP] Configurable v2
  CHANGELOG.md
  lib/spicerack/configurable.rb
  lib/spicerack/configurable/config_builder.rb
  lib/spicerack/configurable/config_delegation.rb
  lib/spicerack/configurable/config_object.rb
  lib/spicerack/configurable/evaluator.rb
  lib/spicerack/configurable/reader.rb
  lib/spicerack/objects/defaults.rb
  lib/spicerack/rspec/configurable/dsl.rb
  lib/spicerack/rspec/configurable/matchers.rb
  lib/spicerack/rspec/configurable/matchers/define_config_option.rb
  lib/spicerack/rspec/configurable/spec_helper.rb
  lib/spicerack/rspec/custom_matchers.rb
  lib/spicerack/rspec/custom_matchers/define_config_option.rb
  lib/spicerack/spec_helper.rb
  spec/integration/example_configurable_class_spec.rb
  spec/spicerack/configurable/config_builder_spec.rb
  spec/spicerack/configurable/config_delegation_spec.rb
  spec/spicerack/configurable/config_object_spec.rb
  spec/spicerack/configurable/reader_spec.rb
  spec/spicerack/configurable_spec.rb
  spec/spicerack/objects/defaults/value_spec.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt.rb
  tablesalt/lib/tablesalt/isolation.rb
  tablesalt/lib/tablesalt/rspec/custom_matchers.rb
  tablesalt/lib/tablesalt/rspec/custom_matchers/isolate.rb
  tablesalt/lib/tablesalt/spec_helper.rb
  tablesalt/spec/spec_helper.rb
  tablesalt/spec/tablesalt/isolation_spec.rb
Labels: Feature

#257 Facet: source
  facet/lib/facet/concerns/collection.rb
  facet/lib/facet/concerns/core.rb
  facet/lib/facet/concerns/record.rb
  facet/spec/facet/collection_spec.rb
  facet/spec/facet/core_spec.rb
  facet/spec/facet/record_spec.rb
  facet/spec/support/shared_context/with_an_example_facet.rb
Labels: Feature

#258 Release 0.17.1
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  collectible/CHANGELOG.md
  collectible/lib/collectible/version.rb
  facet/CHANGELOG.md
  facet/lib/facet/concerns/collection.rb
  facet/lib/facet/concerns/core.rb
  facet/lib/facet/concerns/record.rb
  facet/lib/facet/version.rb
  facet/spec/facet/collection_spec.rb
  facet/spec/facet/core_spec.rb
  facet/spec/facet/record_spec.rb
  facet/spec/support/shared_context/with_an_example_facet.rb
  lib/spicerack/configurable/reader.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spec/integration/example_configurable_class_spec.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#261 Collectible: Delegate `include?`
  collectible/lib/collectible/collection/core.rb
  collectible/spec/collectible/collection/core_spec.rb
Labels: Feature

#262 Release 0.17.3
  CHANGELOG.md
  around_the_world/CHANGELOG.md
  collectible/CHANGELOG.md
  facet/CHANGELOG.md
  redis_hash/CHANGELOG.md
  rspice/CHANGELOG.md
  short_circu_it/CHANGELOG.md
  spicerack-styleguide/CHANGELOG.md
  tablesalt/CHANGELOG.md
  technologic/CHANGELOG.md
Labels: Release

#263 Release 0.17.3
  CHANGELOG.md
  around_the_world/CHANGELOG.md
  collectible/CHANGELOG.md
  collectible/lib/collectible/collection/core.rb
  collectible/spec/collectible/collection/core_spec.rb
  facet/CHANGELOG.md
  redis_hash/CHANGELOG.md
  rspice/CHANGELOG.md
  short_circu_it/CHANGELOG.md
  spicerack-styleguide/CHANGELOG.md
  tablesalt/CHANGELOG.md
  technologic/CHANGELOG.md
Labels: Release

#264 Release 0.17.3
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/lib/around_the_world/version.rb
  collectible/lib/collectible/version.rb
  facet/lib/facet/version.rb
  lib/spicerack/version.rb
  redis_hash/lib/redis_hash/version.rb
  rspice/lib/rspice/version.rb
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  tablesalt/lib/tablesalt/version.rb
  technologic/lib/technologic/version.rb
Labels: Correction
