Repository Freshly/spicerack, pull requests merged in 2020-01, with the labels that each got.

#329 Release 0.20.3
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  collectible/CHANGELOG.md
  collectible/lib/collectible/version.rb
  conjunction/CHANGELOG.md
  conjunction/lib/conjunction/version.rb
  facet/CHANGELOG.md
  facet/lib/facet/version.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  spicery/CHANGELOG.md
  spicery/lib/spicery/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#331 Fix Spec Helper
  conjunction/lib/conjunction/spec_helper.rb
  lib/spicerack/spec_helper.rb
  shared/spec_helper.rb
  spicery/lib/spicery/spec_helper.rb
Labels: Correction

#332 Release 0.20.4
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  collectible/CHANGELOG.md
  collectible/lib/collectible/version.rb
  conjunction/CHANGELOG.md
  conjunction/lib/conjunction/version.rb
  facet/CHANGELOG.md
  facet/lib/facet/version.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  spicery/CHANGELOG.md
  spicery/lib/spicery/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#333 Release 0.20.4
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  collectible/CHANGELOG.md
  collectible/lib/collectible/version.rb
  conjunction/CHANGELOG.md
  conjunction/lib/conjunction/spec_helper.rb
  conjunction/lib/conjunction/version.rb
  facet/CHANGELOG.md
  facet/lib/facet/version.rb
  lib/spicerack/spec_helper.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  shared/spec_helper.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  spicery/CHANGELOG.md
  spicery/lib/spicery/spec_helper.rb
  spicery/lib/spicery/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#334 Stateful Object
  lib/spicerack.rb
  lib/spicerack/objects/output.rb
  lib/spicerack/objects/status.rb
  lib/spicerack/stateful_object.rb
  spec/spicerack/objects/output_spec.rb
  spec/spicerack/objects/status_spec.rb
  spec/spicerack/stateful_object_spec.rb
  spec/spicerack_spec.rb
  spec/support/shared_context/with_an_example_stateful_object.rb
Labels: Correction, Feature

#335 Output Object
  lib/spicerack.rb
  lib/spicerack/output_object.rb
  spec/spicerack/objects/output_spec.rb
  spec/spicerack/objects/status_spec.rb
  spec/spicerack/output_object_spec.rb
  spec/support/shared_context/with_an_example_output_object.rb
  spec/support/shared_context/with_an_example_stateful_object.rb
Labels: Refactoring

#336 Release 0.21.0
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  collectible/CHANGELOG.md
  collectible/lib/collectible/version.rb
  conjunction/CHANGELOG.md
  conjunction/lib/conjunction/version.rb
  facet/CHANGELOG.md
  facet/lib/facet/version.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  spicery/CHANGELOG.md
  spicery/lib/spicery/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#337 Release 0.21.0
  CHANGELOG.md
  Gemfile.lock
  SPICERACK_VERSION
  around_the_world/CHANGELOG.md
  around_the_world/lib/around_the_world/version.rb
  collectible/CHANGELOG.md
  collectible/lib/collectible/version.rb
  conjunction/CHANGELOG.md
  conjunction/lib/conjunction/version.rb
  facet/CHANGELOG.md
  facet/lib/facet/version.rb
  lib/spicerack.rb
  lib/spicerack/objects/output.rb
  lib/spicerack/objects/status.rb
  lib/spicerack/output_object.rb
  lib/spicerack/version.rb
  redis_hash/CHANGELOG.md
  redis_hash/lib/redis_hash/version.rb
  rspice/CHANGELOG.md
  rspice/lib/rspice/version.rb
  short_circu_it/CHANGELOG.md
  short_circu_it/lib/short_circu_it/version.rb
  spec/spicerack/objects/output_spec.rb
  spec/spicerack/objects/status_spec.rb
  spec/spicerack/output_object_spec.rb
  spec/spicerack/stateful_object_spec.rb
  spec/spicerack_spec.rb
  spec/support/shared_context/with_an_example_output_object.rb
  spicerack-styleguide/CHANGELOG.md
  spicerack-styleguide/lib/spicerack/styleguide/version.rb
  spicery/CHANGELOG.md
  spicery/lib/spicery/version.rb
  tablesalt/CHANGELOG.md
  tablesalt/lib/tablesalt/version.rb
  technologic/CHANGELOG.md
  technologic/lib/technologic/version.rb
Labels: Release

#344 Directive
  directive/lib/directive.rb
  directive/lib/directive/config_builder.rb
  directive/lib/directive/config_builder/double_configure.rb
  directive/lib/directive/config_delegation.rb
  directive/lib/directive/config_object.rb
  directive/lib/directive/evaluator.rb
  directive/lib/directive/reader.rb
  directive/spec/directive/config_builder_spec.rb
  directive/spec/directive/config_delegation_spec.rb
  directive/spec/directive/config_object_spec.rb
  directive/spec/directive/reader_spec.rb
  directive/spec/directive_spec.rb
  directive/spec/integration/example_configurable_class_spec.rb
  lib/spicerack/configurable.rb
  lib/spicerack/configurable/config_builder.rb
  lib/spicerack/configurable/config_builder/double_configure.rb
  lib/spicerack/configurable/config_delegation.rb
  lib/spicerack/configurable/config_object.rb
  lib/spicerack/configurable/evaluator.rb
  lib/spicerack/configurable/reader.rb
Labels: Feature

#346 don't convert hashes to arrays please
  technologic/lib/technologic/logger.rb
  technologic/spec/technologic/logger_spec.rb
Labels: Maintenance
